#!/usr/bin/env bash

# 🚀 QUICK REFERENCE - Metaverso 6G RAG
# Copy-paste dos comandos mais usados

echo "📋 METAVERSO 6G RAG - QUICK REFERENCE"
echo "════════════════════════════════════"
echo ""
echo "🔧 SETUP INICIAL"
echo "  chmod +x setup.sh && ./setup.sh"
echo ""
echo "📝 CONFIGURAR VARIÁVEIS"
echo "  cp .env.example .env"
echo "  nano .env  # Adicionar GEMINI_API_KEY"
echo ""
echo "📚 INGESTÃO DE PDFs"
echo "  python -m app.ingest ingest"
echo "  python -m app.ingest status"
echo "  python -m app.ingest reset"
echo ""
echo "🧪 TESTES"
echo "  python test_config.py        # Validar ambiente"
echo "  python test_api.py           # Suite de testes"
echo "  python test_api.py -i        # Modo interativo"
echo "  python test_api.py -q \"pergunta\" # Query específica"
echo ""
echo "🌐 SERVIDOR"
echo "  # Desenvolvimento"
echo "  uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
echo ""
echo "  # Produção/Render"
echo "  uvicorn app.main:app --host 0.0.0.0 --port \$PORT"
echo ""
echo "📡 API ENDPOINTS"
echo "  GET  http://localhost:8000/health"
echo "  GET  http://localhost:8000/"
echo "  POST http://localhost:8000/query"
echo ""
echo "💻 CURL EXAMPLES"
echo "  # Health check"
echo "  curl http://localhost:8000/health"
echo ""
echo "  # Query"
echo "  curl -X POST http://localhost:8000/query \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"question\": \"O que é 6G?\"}'"
echo ""
echo "🐳 DOCKER"
echo "  docker build -t metaverso-rag ."
echo "  docker run -p 8000:8000 -e GEMINI_API_KEY=seu_token metaverso-rag"
echo ""
echo "🚀 GIT & DEPLOY"
echo "  git add ."
echo "  git commit -m 'Metaverso 6G RAG'"
echo "  git push"
echo "  # Render fará deploy automático"
echo ""
echo "📂 ESTRUTURA"
echo "  metaverso/"
echo "  ├── app/              # Código principal"
echo "  ├── pdfs/             # PDFs para ingestão"
echo "  ├── render.yaml       # Config Render"
echo "  ├── requirements.txt  # Dependências"
echo "  ├── README.md         # Guia completo"
echo "  └── test_*.py         # Testes"
echo ""
echo "📊 DOCUMENTAÇÃO"
echo "  • README.md ..................... Guia principal"
echo "  • SETUP_SUMMARY.md ............. Resumo técnico"
echo "  • FINAL_SUMMARY.txt ............ Guia visual"
echo "  • EXECUTIVE_SUMMARY.md ........ Resumo executivo"
echo ""
echo "✨ STATUS: PRONTO PARA PRODUÇÃO ✨"
