#!/bin/bash
# 🔧 QUICK REFERENCE: Memory Optimization Deployment
# Comandos rápidos para deploy da correção do erro 502

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║      DEPLOYMENT REFERENCE: Memory Optimization v1.1.0         ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 CHECKLIST PRÉ-DEPLOY"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1️⃣  PREPARAÇÃO"
echo "   □ Revisar QUICK_FIX.md"
echo "   □ Revisar CHANGELOG.md"
echo ""
echo "2️⃣  VALIDAÇÃO LOCAL"
echo "   □ pip install -r requirements.txt"
echo "   □ python -m uvicorn app.main:app --reload &"
echo "   □ python test_memory_optimization.py"
echo ""
echo "3️⃣  VERIFICAÇÃO DE CÓDIGO"
echo "   □ grep -n 'LAZY_LOAD_MODELS = True' app/config.py"
echo "   □ grep -n 'class ModelManager' app/rag.py"
echo "   □ grep -n '@with_timeout' app/main.py"
echo "   □ grep 'psutil' requirements.txt"
echo ""
echo "4️⃣  GIT OPERATIONS"
echo "   □ git status (verificar mudanças)"
echo "   □ git add ."
echo "   □ git commit -m 'Fix: Lazy loading + Memory optimization (resolves 502)'"
echo "   □ git push origin main"
echo ""
echo "5️⃣  PÓS-DEPLOY (aguarde 2-3 minutos)"
echo "   □ curl -s https://seu-dominio/api/v1/health | json_pp"
echo "   □ curl -s https://seu-dominio/api/v1/memory | json_pp"
echo "   □ Fazer requisição POST /api/v1/ask"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "🚀 COMANDOS"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "LOCAL SETUP & TEST:"
echo "─────────────────────────────────────────────────────────────"
echo "$ pip install -r requirements.txt"
echo "$ python -m uvicorn app.main:app --reload"
echo ""
echo "[em outro terminal]"
echo "$ python test_memory_optimization.py"
echo ""
echo "DEPLOY:"
echo "─────────────────────────────────────────────────────────────"
echo "$ git add ."
echo "$ git commit -m 'Fix: Lazy loading + Memory optimization'"
echo "$ git push origin main"
echo ""
echo "VERIFICATION:"
echo "─────────────────────────────────────────────────────────────"
echo "$ curl https://seu-dominio/api/v1/health"
echo "$ curl https://seu-dominio/api/v1/memory"
echo ""
echo "CONTINUOUS MONITORING:"
echo "─────────────────────────────────────────────────────────────"
echo "$ watch -n 5 'curl -s https://seu-dominio/api/v1/memory | json_pp'"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "📊 EXPECTED METRICS"
echo "═══════════════════════════════════════════════════════════════"
echo ""
printf "%-30s | %-15s | %-15s\n" "Metric" "Before" "After"
echo "───────────────────────────────────────────────────────────────"
printf "%-30s | %-15s | %-15s\n" "Initial Memory" "600 MB" "150 MB (-75%)"
printf "%-30s | %-15s | %-15s\n" "Per Request" "200 MB" "80 MB (-60%)"
printf "%-30s | %-15s | %-15s\n" "Peak Memory" "1.2 GB" "600 MB (-50%)"
printf "%-30s | %-15s | %-15s\n" "Crashes/day" "5+" "0 (100%)"
printf "%-30s | %-15s | %-15s\n" "Stability" "Unstable" "Stable ✓"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "✅ SUCCESS INDICATORS"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "✓ All 5 test requests complete"
echo "✓ Memory stays ~300-400 MB (doesn't grow)"
echo "✓ Response time: <5s per request"
echo "✓ Timeout protection active (30s)"
echo "✓ No error 502 after multiple requests"
echo "✓ GC cleanup visible in logs"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "❌ TROUBLESHOOTING"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Problem: Still getting 502"
echo "├─ Check Render logs: dashboard.render.com → Logs"
echo "├─ Verify psutil: grep psutil requirements.txt"
echo "├─ Check config: grep REQUEST_TIMEOUT app/config.py"
echo "└─ If persistent: Try ENABLE_RERANKER=false"
echo ""
echo "Problem: Tests fail locally"
echo "├─ Make sure pip install worked: pip list | grep psutil"
echo "├─ Check Python version: python --version"
echo "├─ Verify imports: python -c 'import psutil'"
echo "└─ Check syntax: python -m py_compile app/*.py"
echo ""
echo "Problem: Deploy failed"
echo "├─ Check git status: git status"
echo "├─ View logs: git log --oneline -5"
echo "└─ Rollback: git revert <commit_hash> && git push"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "📚 DOCUMENTATION FILES"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "QUICK START (2-5 minutes)"
echo "  → QUICK_FIX.md (summarized version)"
echo ""
echo "DEPLOYMENT (10-15 minutes)"
echo "  → DEPLOY_GUIDE.md (step by step)"
echo ""
echo "TECHNICAL DETAILS (30+ minutes)"
echo "  → MEMORY_OPTIMIZATION.md (deep dive)"
echo ""
echo "VISUAL EXPLANATION (10 minutes)"
echo "  → VISUAL_SUMMARY.md (diagrams + charts)"
echo ""
echo "COMPLETE REFERENCE"
echo "  → CHANGELOG.md (all modifications)"
echo "  → README_FIX_502.md (main document)"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "🎯 KEY TAKEAWAYS"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. ModelManager = Lazy Loading of ML Models"
echo "   → Only loaded when needed, not at startup"
echo ""
echo "2. Garbage Collection = Proper Memory Cleanup"
echo "   → PDFs freed after use, gc.collect() called"
echo ""
echo "3. Reduced Parameters = Less memory per request"
echo "   → INITIAL_RETRIEVAL_K: 12 → 6"
echo "   → MAX_CONTEXT_TOKENS: 3500 → 2000"
echo ""
echo "4. Timeout Protection = No frozen requests"
echo "   → @with_timeout(30s) prevents memory leak"
echo ""
echo "5. Monitoring = Visibility into production"
echo "   → GET /api/v1/memory shows memory usage"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "✨ DEPLOYMENT TIME: 2-3 minutes"
echo "✨ DOWNTIME: 0 seconds"
echo "✨ RISK: Very low (isolated changes)"
echo "✨ ROLLBACK: Simple git revert if needed"
echo "═══════════════════════════════════════════════════════════════"
echo ""
