services:
  - type: web
    name: metaverso-rag
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: CHROMA_PERSIST_DIR
        value: /var/data/chroma
      - key: API_KEY
        sync: false

disks:
  - name: chroma-data
    sizeGB: 5
    mountPath: /var/data/chroma
